apiVersion: v1
kind: Service
metadata: 
  name: worker
spec: 
  selector:
    app: worker
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 6379
    - protocol: TCP
      port: 80
      targetPort: 5432
