apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
spec:
  selector:
    matchLabels:
      app: hello-python
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: voting-app
        image: mshaibek/voting-app_vote:1.0
        ports:
        - containerPort: 80
#          targetPort: 6379
